name: Selenium CI + Allure Deploy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write  # necesario para pushear a gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests and store Allure results
        run: |
          mkdir -p reports/allure-results
          pytest --alluredir=reports/allure-results --browser=chrome --headless

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure.zip -d /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: Generate Allure report
        run: |
          mkdir -p reports/allure-report
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-report
