name: Selenium CI + Allure Deploy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image for tests
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: selenium-tests:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Selenium tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            selenium-tests

      - name: Ensure Allure report exists
        run: |
          if [ ! -f reports/allure-report/index.html ]; then
            echo "❌ Allure report not generated!"
            exit 1
          fi

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-report
          commit_message: "chore: deploy Allure report 🚀"
