name: Selenium CI + Allure Deploy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: selenium-tests:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run tests and generate Allure results
        run: |
          mkdir -p reports
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            selenium-tests

      - name: Generate Allure report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            mcr.microsoft.com/playwright:v1.39.0-focal \
            bash -c "apt-get update && apt-get install -y allure && \
            allure generate /app/reports -o /app/reports/allure-report --clean"

      - name: Verify report structure
        run: |
          echo "=== Estructura del reporte ==="
          find reports/allure-report -type f
          [ -f reports/allure-report/index.html ] || exit 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report
          retention-days: 1

  deploy:
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3