name: Selenium CI + Allure Deploy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout GitHub Pages with previous Allure reports
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image for tests
        run: make build

      - name: Run Selenium tests and store Allure results
        run: make test-dc

      - name: Generate Allure test report with history
        run: make dc-report

      - name: Move report for GitHub Pages
        run: |
          mkdir -p gh-pages-dir/builds/tests
          cp -r reports/allure-report/* gh-pages-dir/builds/tests/

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages-dir
