name: Selenium CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-

      - name: Build Docker image for tests
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: selenium-tests:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            selenium-tests

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report
