name: Run Tests and Publish Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          mkdir -p reports/allure-results
          pytest --alluredir=reports/allure-results

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.zip
          unzip allure.zip -d /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Copy history from previous report
        run: |
          mkdir -p reports/allure-results/history
          if [ -d gh-pages-dir/reports/allure-report/history ]; then
            cp -R gh-pages-dir/reports/allure-report/history reports/allure-results/
          fi

      - name: Generate Allure report
        run: |
          mkdir -p reports/allure-report
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-report
